"""add reporter_id to issues

Revision ID: 9c7d6c4b90d0
Revises: e702cbc5c85b
Create Date: 2026-05-06 16:59:07.479860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c7d6c4b90d0'
down_revision = 'e702cbc5c85b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('reporter_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'issues', 'users', ['reporter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_column('issues', 'reporter_id')
    # ### end Alembic commands ###
